plugin:
  name: Fixture placement
  UUID: f86d7b11-096b-4f0c-8702-5bce3a45b88a
  version: 2026.0.0
  developer: allplan-gmbh
  default-language: en
  min-allplan-version: 2026
installation:
  target-location: USR

tools:
  - id: place-fixture
    pyp: Library\Allplan GmbH\Fixture placement.pyp
    display-name:
      en: Fixture placement
    icons:
      small: PythonPartsActionbar\allplan_gmbh\fixture_placement\fixture_placement_24.png
      large: PythonPartsActionbar\allplan_gmbh\fixture_placement\fixture_placement_128.png
