name: Release Allep

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create allep file
        uses: vimtor/action-zip@v1.1
        with:
          files: Library/ PythonPartsScripts/ install-config.yml
          recursive: false
          dest: FixturePlacement.allep

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            FixturePlacement.allep