name: Release Allep plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout specific directories and file
        run: |
          mkdir -p Library PythonPartsScripts
          git checkout HEAD -- Library
          git checkout HEAD -- PythonPartsScripts
          git checkout HEAD -- install-config.yml

      - name: Create allep file
        run: |
          zip -r FixturePlacement.allep Library PythonPartsScripts install-config.yml

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            FixturePlacement.allep